### ISSUE TITLE
[Question] Report generation and download using FOSSology.REST.shell

### ISSUE THREAD

**Issue by avneetsngh** [fossology/FOSSology.REST.shell#1]
Hi @NicolasToussaint  ,

I was wondering if there any plans for including the ability to trigger report generation and download by using FOSSology.REST.shell ?
I feel that in this way, it would be possible to fully automate the activity of obtaining licenses for an input file using this script

eg usecase:
input_file -> FOSSology.REST.shell -> report from Fossology

If the above is planned, would it be okay if I contribute a patch for it?

**Comment by NicolasToussaint** [comment]
Hi @avneetsngh ,
We won't use that specific feature straight away, but it's certainly a valuable feature to be added to the REST client.

It would be awesome if you wanted to develop it & contribute!

**Comment by avneetsngh** [comment]
Thank you :) 
I will develop this feature and share the changes soon

**Comment by avneetsngh** [comment]
Hi @NicolasToussaint ,
I have created the pull request " https://github.com/fossology/FOSSology.REST.shell/pull/2 " implementing this feature

**Comment by avneetsngh** [comment]
Thank you for accepting the PR
I will close this issue now
